# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51b815a2cd09523b02de0f5bfb6e033a41778fdb6bb5633767a77bf4955b5823723c6e178492b3776def45a00a98599b3050c326d8635b85b591f021f1dde079

test:
  secret_key_base: b04f139d6e9c2f23adfb325f150bf0aedb5dca5b12ee0ddffd8b093f066ccf2168b981e346d4a1198391143abbfa53bef8136e3ce6235203070ef632cf06ab27

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
